version: '3.6'
services:
  php:
    build: .docker/php
    expose:
      - '9000'
    volumes:
      - ./.docker/php/logs:/var/log
      - ./app:/var/www
    environment:
      PHP_XDEBUG_ENABLED: 1

  web:
    image: nginx:1.19-alpine
    ports:
      - '8080:80'
    depends_on:
      - php
    volumes:
        - ./.docker/nginx/logs:/var/log/nginx
        - ./app:/var/www
        - ./.docker/nginx/sites-enabled/:/etc/nginx/sites-enabled
        - ./.docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf

  mariadb:
      image: mariadb:10.5
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mariadb
        MYSQL_USER: local
        MYSQL_PASSWORD: local
      ports:
        - "33066:3306"
      volumes:
        - ./.docker/mariadb:/var/lib/mysql

  zoo:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/data
      - ./zk-single-kafka-single/zoo1/datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka1
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo
